<a href="https://colab.research.google.com/github/benxuu/BeiDreamEasyUi/blob/master/%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0_%E4%BA%BA%E6%95%99_%E8%B0%A2%E7%90%BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

第三章，初识TensorFlow，预测总分的计算权重，答案为6,3,1；代码sore1c.py，

In [2]:
import tensorflow as tf
x1=tf.placeholder(dtype=tf.float32)
x2=tf.placeholder(dtype=tf.float32)
x3=tf.placeholder(dtype=tf.float32)

yTrain = tf.placeholder(dtype=tf.float32)
w1=tf.Variable(0.1,dtype=tf.float32)
w2=tf.Variable(0.1,dtype=tf.float32)
w3=tf.Variable(0.1,dtype=tf.float32)

n1=x1*w1
n2=x2*w2
n3=x3*w3

y=n1+n2+n3

loss=tf.abs(y-yTrain)
optimizer=tf.train.RMSPropOptimizer(0.001)
train=optimizer.minimize(loss)
sess=tf.Session()
init=tf.global_variables_initializer()
sess.run(init)
for i in range(6000):
    result=sess.run([train,x1,x2,x3,w1,w2,w3,y,yTrain,loss],feed_dict={x1:90,x2:80,x3:70,yTrain:85})
    result=sess.run([train,x1,x2,x3,w1,w2,w3,y,yTrain,loss],feed_dict={x1:98,x2:95,x3:87,yTrain:96})
    if (i%1000==0):
        print(result)

[None, array(98., dtype=float32), array(95., dtype=float32), array(87., dtype=float32), 0.10554425, 0.10563005, 0.1056722, 28.884804, array(96., dtype=float32), 67.1152]
[None, array(98., dtype=float32), array(95., dtype=float32), array(87., dtype=float32), 0.3986066, 0.33069745, 0.2951451, 96.45682, array(96., dtype=float32), 0.45681763]
[None, array(98., dtype=float32), array(95., dtype=float32), array(87., dtype=float32), 0.45939523, 0.31527463, 0.24004416, 96.15514, array(96., dtype=float32), 0.15514374]
[None, array(98., dtype=float32), array(95., dtype=float32), array(87., dtype=float32), 0.522271, 0.30200568, 0.18714713, 96.45438, array(96., dtype=float32), 0.45437622]
[None, array(98., dtype=float32), array(95., dtype=float32), array(87., dtype=float32), 0.58308536, 0.28658286, 0.13205872, 96.15633, array(96., dtype=float32), 0.1563263]
[None, array(98., dtype=float32), array(95., dtype=float32), array(87., dtype=float32), 0.5848418, 0.2880892, 0.13343368, 95.99221, array(96., 

第四章：简化神经网络模型，使用张量代替原来的独立变量输入，代码score1d.py

In [5]:
import tensorflow as tf
x=tf.placeholder(shape=[3],dtype=tf.float32)
yTrain = tf.placeholder(shape=[],dtype=tf.float32)
w=tf.Variable(tf.zeros([3]),dtype=tf.float32)
n=x*w
y=tf.reduce_sum(n)

loss=tf.abs(y-yTrain)
optimizer=tf.train.RMSPropOptimizer(0.001)
train=optimizer.minimize(loss)
sess=tf.Session()
init=tf.global_variables_initializer()
sess.run(init)
for i in range(6000):
    result=sess.run([train,x,w,y,yTrain,loss],feed_dict={x:[90,80,70],yTrain:85})
    result=sess.run([train,x,w,y,yTrain,loss],feed_dict={x:[98,95,87],yTrain:96})
    if (i%1000==0):
        print(result)

[None, array([98., 95., 87.], dtype=float32), array([0.00554424, 0.00563004, 0.0056722 ], dtype=float32), 0.88480234, array(96., dtype=float32), 95.1152]
[None, array([98., 95., 87.], dtype=float32), array([0.39422113, 0.32977572, 0.29594862], dtype=float32), 96.009384, array(96., dtype=float32), 0.009384155]
[None, array([98., 95., 87.], dtype=float32), array([0.45708835, 0.31650677, 0.24303839], dtype=float32), 96.306625, array(96., dtype=float32), 0.30662537]
[None, array([98., 95., 87.], dtype=float32), array([0.5178843 , 0.30108395, 0.18794999], dtype=float32), 96.006775, array(96., dtype=float32), 0.0067749023]
[None, array([98., 95., 87.], dtype=float32), array([0.5807772 , 0.287815  , 0.13505295], dtype=float32), 96.307686, array(96., dtype=float32), 0.30768585]
[None, array([98., 95., 87.], dtype=float32), array([0.58203536, 0.28629485, 0.13208804], dtype=float32), 96.02862, array(96., dtype=float32), 0.028617859]


在TensorFlow中查看和设置张量的形态

In [6]:
import tensorflow as tf
x=tf.placeholder(dtype=tf.float32)
xShape=tf.shape(x)
sess=tf.Session()
result=sess.run(xShape,feed_dict={x:8})
print(result)
result=sess.run(xShape,feed_dict={x:[1,2,3]})
print(result)
result=sess.run(xShape,feed_dict={x:[[1,2,3],[4,5,6]]})
print(result)

[]
[3]
[2 3]


用softmax函数来规范可变参数，继续改进sorce预测

In [8]:
import tensorflow as tf
x=tf.placeholder(shape=[3],dtype=tf.float32)
yTrain = tf.placeholder(shape=[],dtype=tf.float32)
w=tf.Variable(tf.zeros([3]),dtype=tf.float32)
wn=tf.nn.softmax(w)
n=x*wn
y=tf.reduce_sum(n)

loss=tf.abs(y-yTrain)
optimizer=tf.train.RMSPropOptimizer(0.1)
train=optimizer.minimize(loss)
sess=tf.Session()
init=tf.global_variables_initializer()
sess.run(init)
for i in range(5000):
    result=sess.run([train,x,w,wn,y,yTrain,loss],feed_dict={x:[90,80,70],yTrain:85})
    result=sess.run([train,x,w,wn,y,yTrain,loss],feed_dict={x:[98,95,87],yTrain:96})
    if (i%1000==0):
        print(result[3])

[0.413998   0.32727832 0.2587237 ]
[0.53844655 0.38167572 0.0798777 ]
[0.524928   0.39789757 0.07717442]
[0.60777235 0.32559934 0.06662827]
[0.5192314  0.39264944 0.08811913]


作业：标量【3，,2]与标量7相乘的结果

In [10]:
import tensorflow as tf
x=tf.placeholder(shape=[3,2],dtype=tf.float32)
y=x*7
sess=tf.Session()
init=tf.global_variables_initializer()
sess.run(init)
result=sess.run([x,y],feed_dict={x:[[1,2],[3,4],[90,80]]})
print(result)

[array([[ 1.,  2.],
       [ 3.,  4.],
       [90., 80.]], dtype=float32), array([[  7.,  14.],
       [ 21.,  28.],
       [630., 560.]], dtype=float32)]


第五章：神经网络解决非线性问题，二分类问题

In [0]:
import tensorflow as tf
x=tf.placeholder(shape=[3],dtype=tf.float32)
yTrain = tf.placeholder(shape=[],dtype=tf.float32)
w=tf.Variable(tf.zeros([3]),dtype=tf.float32)
wn=tf.nn.softmax(w)
n1=x*wn
n2=tf.reduce_sum(n1)
y=tf.nn.sigmoid(n2)

loss=tf.abs(y-yTrain)
optimizer=tf.train.RMSPropOptimizer(0.1)
train=optimizer.minimize(loss)
sess=tf.Session()
init=tf.global_variables_initializer()
sess.run(init)
for i in range(5000):
    result=sess.run([train,x,w,wn,y,yTrain,loss],feed_dict={x:[90,80,70],yTrain:85})
    result=sess.run([train,x,w,wn,y,yTrain,loss],feed_dict={x:[98,95,87],yTrain:96})
    if (i%1000==0):
        print(result[3])

生成随机训练数据

In [11]:
import random
random.seed()
xData=[int(random.random()*101),int(random.random()*101),int(random.random()*101)]
xAll=xData[0]*0.6+xData[1]*0.3+xData[2]*0.1
if xAll>=95:
  yTrainData=1
else:
  yTrainData=0
print("xData:%s" % xData)
print("yTrainData:%s" % yTrainData)


xData:[40, 74, 9]
yTrainData:0
